// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwazxzzuizyvbxgmuuwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3YXp4enp1aXp5dmJ4Z211dXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTU2NjIsImV4cCI6MjA3MDQ5MTY2Mn0.8yuHvwS8ZAkw6v-AZNTu0QDTgDVI4Kg69hJT3IOwxlM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});