// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbindpnlllxtfqbgvyxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiaW5kcG5sbGx4dGZxYmd2eXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTE3MTgsImV4cCI6MjA2NTg4NzcxOH0.lbhf6vzxm0oeavaY0e0tjcLCisfVk84JxZpp8kQ5yE0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});